// AUTO-GENERATED by codeview. Do not edit.
@file:OptIn(
    androidx.compose.ui.tooling.data.UiToolingDataApi::class,
    androidx.compose.ui.test.ExperimentalTestApi::class,
    androidx.compose.runtime.InternalComposeApi::class,
)
@file:Suppress("INVISIBLE_REFERENCE", "INVISIBLE_MEMBER")

package com.rohittp.plugables.codeview.generated

import android.graphics.Bitmap
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.key
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.runtime.tooling.CompositionData
import androidx.compose.ui.graphics.asAndroidBitmap
import androidx.compose.ui.semantics.SemanticsNode
import androidx.compose.ui.semantics.SemanticsProperties
import androidx.compose.ui.semantics.getOrNull
import androidx.compose.ui.test.ComposeUiTest
import androidx.compose.ui.test.captureToImage
import androidx.compose.ui.test.onRoot
import androidx.compose.ui.tooling.data.ContextCache
import androidx.compose.ui.tooling.data.SourceContext
import androidx.compose.ui.tooling.data.mapTree
import java.io.File

object CodeviewRuntime {

    data class PreviewMeta(
        val id: String,
        val fqn: String,
        val displayName: String,
        val sourceFile: String,
        val sourceLine: Int,
        val sourceHash: String,
    )

    /**
     * Single-test entry point. Compose UI test allows exactly one [ComposeUiTest.setContent] call
     * per test, so we set it once with a [androidx.compose.runtime.mutableStateOf] holding the
     * current preview's content. Each iteration swaps the state value and a `key(...)` block
     * forces a fresh composition subtree so previous slot-tree state doesn't leak between
     * previews. A render exception in any preview is caught, recorded in that preview's
     * `renderError` sidecar field, and the loop continues.
     */
    fun runBatch(
        uiTest: ComposeUiTest,
        outputDir: File,
        registry: List<Pair<PreviewMeta, @Composable () -> Unit>>,
        skippedIds: Set<String>,
    ) {
        outputDir.mkdirs()
        val publishToSdcard = File(outputDir, "__codeview_published__").exists()
        if (publishToSdcard) preparePublishDir()

        val record = androidx.compose.ui.tooling.CompositionDataRecord.Companion.create()
        var currentKey by mutableStateOf("")
        var currentContent by mutableStateOf<@Composable () -> Unit>({})

        uiTest.setContent {
            // `key(currentKey)` forces a brand-new subtree per preview so each render starts
            // from a clean slot table — no `remember` leak from the previous preview.
            key(currentKey) {
                androidx.compose.ui.tooling.Inspectable(record) {
                    currentContent()
                }
            }
        }
        // Establish the empty initial composition.
        uiTest.waitForIdle()

        for ((meta, content) in registry) {
            if (meta.id in skippedIds) continue
            try {
                // Swap content and re-key so Inspectable adds a fresh CompositionData.
                currentKey = meta.id
                currentContent = content
                uiTest.waitForIdle()
                renderOne(uiTest, outputDir, meta, record, publishToSdcard)
            } catch (t: Throwable) {
                System.err.println("[codeview] Render failed for ${meta.id}: ${t.message}")
                writeErrorSidecar(outputDir, meta, t, publishToSdcard)
            }
        }
    }

    private fun renderOne(
        uiTest: ComposeUiTest,
        outputDir: File,
        meta: PreviewMeta,
        record: androidx.compose.ui.tooling.CompositionDataRecord,
        publishToSdcard: Boolean,
    ) {
        // `record.store` accumulates a CompositionData per Inspectable composition. With the
        // `key(currentKey)` swap, the most recent CompositionData reflects the current preview;
        // older entries reference subtrees that have been disposed. mapTree on a disposed table
        // yields no live nodes, so iterating all entries is safe — only the current one
        // produces nodes — but for clarity we walk only the most recently added entry.
        val tables: List<CompositionData> = record.store.toList()
        val currentTable = tables.lastOrNull()

        val nodes = mutableListOf<NodeJson>()
        val cache = ContextCache()
        val nextIdHolder = intArrayOf(1)
        currentTable?.mapTree<NodeJson>({ _, ctx, childNodes ->
            val box = ctx.bounds
            if (box.right <= box.left || box.bottom <= box.top) return@mapTree null
            val myId = nextIdHolder[0]
            nextIdHolder[0] = myId + 1
            val loc = ctx.location
            val node = NodeJson(
                id = myId,
                name = ctx.name ?: "Group",
                x = box.left, y = box.top,
                w = box.right - box.left, h = box.bottom - box.top,
                sourceFileName = loc?.sourceFile,
                packageHash = loc?.packageHash ?: 0,
                line = loc?.lineNumber ?: -1,
                parentId = null,
            )
            nodes.add(node)
            childNodes.forEach { it.parentId = myId }
            node
        }, cache)

        val renderedTexts = mutableListOf<String>()
        try {
            val rootSem = uiTest.onRoot().fetchSemanticsNode()
            collectRenderedText(rootSem, renderedTexts)
        } catch (t: Throwable) {
            System.err.println("[codeview] Could not collect semantics text for ${meta.id}: ${t.message}")
        }

        var bitmapWidth = 0
        var bitmapHeight = 0
        val pngFile = File(outputDir, "${meta.id}.png")
        try {
            val bitmap: Bitmap = uiTest.onRoot().captureToImage().asAndroidBitmap()
            bitmapWidth = bitmap.width
            bitmapHeight = bitmap.height
            pngFile.outputStream().use { os -> bitmap.compress(Bitmap.CompressFormat.PNG, 100, os) }
        } catch (t: Throwable) {
            System.err.println("[codeview] Skipping PNG capture for ${meta.id}: ${t.message}")
        }

        val sidecar = File(outputDir, "${meta.id}.json")
        sidecar.writeText(buildJson(meta, bitmapWidth, bitmapHeight, nodes, renderedTexts, renderError = null))

        if (publishToSdcard) publish(sidecar, pngFile)
    }

    private fun writeErrorSidecar(
        outputDir: File,
        meta: PreviewMeta,
        t: Throwable,
        publishToSdcard: Boolean,
    ) {
        // Keep the error message short — long stack traces inflate sidecar JSON for no real
        // user value (the relevant info is the exception class + message).
        val msg = "${t.javaClass.simpleName}: ${t.message ?: "(no message)"}"
        val sidecar = File(outputDir, "${meta.id}.json")
        sidecar.writeText(buildJson(meta, 0, 0, emptyList(), emptyList(), renderError = msg))
        if (publishToSdcard) publish(sidecar, pngFile = null)
    }

    /**
     * For instrumented runs the app is uninstalled by AGP after the test, so files in
     * externalCacheDir disappear before the host can pull them. Use UiAutomation to shell-out
     * (uid 2000, has write access to /sdcard) and copy sidecars to a shared location that
     * survives uninstall. The sentinel file `__codeview_published__` flags this mode. Wipe the
     * publish dir up front so leaked sidecars from a previous interrupted run don't pollute
     * this run's output.
     */
    private fun preparePublishDir() {
        try {
            val ui = androidx.test.platform.app.InstrumentationRegistry
                .getInstrumentation().uiAutomation
            val publishDir = "/sdcard/codeview-sidecars"
            ui.executeShellCommand("rm -rf $publishDir").close()
            ui.executeShellCommand("mkdir -p $publishDir").close()
            ui.executeShellCommand("chmod 777 $publishDir").close()
        } catch (t: Throwable) {
            System.err.println("[codeview] Failed to prepare publish dir: ${t.message}")
        }
    }

    private fun publish(sidecar: File, pngFile: File?) {
        try {
            val ui = androidx.test.platform.app.InstrumentationRegistry
                .getInstrumentation().uiAutomation
            val publishDir = "/sdcard/codeview-sidecars"
            sidecar.setReadable(true, false)
            if (pngFile != null && pngFile.exists()) pngFile.setReadable(true, false)
            ui.executeShellCommand("cp ${sidecar.absolutePath} $publishDir/${sidecar.name}").close()
            if (pngFile != null && pngFile.exists()) {
                ui.executeShellCommand("cp ${pngFile.absolutePath} $publishDir/${pngFile.name}").close()
            }
        } catch (t: Throwable) {
            System.err.println("[codeview] Failed to publish sidecars for ${sidecar.name}: ${t.message}")
        }
    }

    private class NodeJson(
        val id: Int,
        val name: String,
        val x: Int, val y: Int, val w: Int, val h: Int,
        val sourceFileName: String?,
        val packageHash: Int,
        val line: Int,
        var parentId: Int?,
    )

    /**
     * Walks the semantics tree and appends every visible text-bearing string to [out].
     * Text comes from `Text` (rendered AnnotatedStrings), `EditableText` (TextField content),
     * and `ContentDescription`. Empty/blank strings are skipped.
     */
    private fun collectRenderedText(node: SemanticsNode, out: MutableList<String>) {
        val cfg = node.config
        cfg.getOrNull(SemanticsProperties.Text)?.forEach { ann ->
            val s = ann.text
            if (s.isNotBlank()) out.add(s)
        }
        cfg.getOrNull(SemanticsProperties.EditableText)?.let { ann ->
            val s = ann.text
            if (s.isNotBlank()) out.add(s)
        }
        cfg.getOrNull(SemanticsProperties.ContentDescription)?.forEach { s ->
            if (s.isNotBlank()) out.add(s)
        }
        node.children.forEach { collectRenderedText(it, out) }
    }

    private fun buildJson(
        meta: PreviewMeta,
        imageWidth: Int,
        imageHeight: Int,
        nodes: List<NodeJson>,
        renderedTexts: List<String>,
        renderError: String?,
    ): String = buildString {
        append("{")
        append("\"schemaVersion\":3,")
        append("\"id\":").append(j(meta.id)).append(',')
        append("\"previewFqn\":").append(j(meta.fqn)).append(',')
        append("\"displayName\":").append(j(meta.displayName)).append(',')
        append("\"sourceFile\":").append(j(meta.sourceFile)).append(',')
        append("\"sourceLine\":").append(meta.sourceLine).append(',')
        append("\"sourceHash\":").append(j(meta.sourceHash)).append(',')
        append("\"imageWidth\":").append(imageWidth).append(',')
        append("\"imageHeight\":").append(imageHeight).append(',')
        if (renderError != null) {
            append("\"renderError\":").append(j(renderError)).append(',')
        }
        append("\"renderedTexts\":[")
        append(renderedTexts.joinToString(",") { j(it) })
        append("],")
        append("\"nodes\":[")
        append(nodes.joinToString(",") { n ->
            buildString {
                append('{')
                append("\"id\":").append(n.id).append(',')
                append("\"name\":").append(j(n.name)).append(',')
                append("\"bounds\":{\"x\":").append(n.x).append(",\"y\":").append(n.y)
                append(",\"width\":").append(n.w).append(",\"height\":").append(n.h).append("},")
                append("\"sourceFileName\":").append(if (n.sourceFileName == null) "null" else j(n.sourceFileName)).append(',')
                append("\"packageHash\":").append(n.packageHash).append(',')
                append("\"line\":").append(n.line).append(',')
                append("\"parentId\":").append(n.parentId?.toString() ?: "null")
                append('}')
            }
        })
        append("]}")
    }

    private fun j(s: String): String {
        val sb = StringBuilder(s.length + 2).append('"')
        for (c in s) when (c) {
            '\\' -> sb.append("\\\\")
            '"' -> sb.append("\\\"")
            '\n' -> sb.append("\\n")
            '\r' -> sb.append("\\r")
            '\t' -> sb.append("\\t")
            else -> if (c.code < 0x20) sb.append("\\u%04x".format(c.code)) else sb.append(c)
        }
        sb.append('"')
        return sb.toString()
    }
}
