// AUTO-GENERATED by codeview. Do not edit.
@file:OptIn(
    androidx.compose.ui.tooling.data.UiToolingDataApi::class,
    androidx.compose.ui.test.ExperimentalTestApi::class,
    androidx.compose.runtime.InternalComposeApi::class,
)
@file:Suppress("INVISIBLE_REFERENCE", "INVISIBLE_MEMBER")

package com.rohittp.plugables.codeview.generated

import android.graphics.Bitmap
import androidx.compose.runtime.Composable
import androidx.compose.runtime.tooling.CompositionData
import androidx.compose.ui.graphics.asAndroidBitmap
import androidx.compose.ui.semantics.SemanticsNode
import androidx.compose.ui.semantics.SemanticsProperties
import androidx.compose.ui.semantics.getOrNull
import androidx.compose.ui.test.ComposeUiTest
import androidx.compose.ui.test.captureToImage
import androidx.compose.ui.test.onRoot
import androidx.compose.ui.tooling.data.ContextCache
import androidx.compose.ui.tooling.data.SourceContext
import androidx.compose.ui.tooling.data.mapTree
import java.io.File

object CodeviewRuntime {

    fun renderAndCapture(
        uiTest: ComposeUiTest,
        outputDir: File,
        previewId: String,
        previewFqn: String,
        previewDisplayName: String,
        previewSourceFile: String,
        previewSourceLine: Int,
        content: @Composable () -> Unit,
    ) {
        val record = androidx.compose.ui.tooling.CompositionDataRecord.Companion.create()
        uiTest.setContent {
            androidx.compose.ui.tooling.Inspectable(record) {
                content()
            }
        }
        uiTest.waitForIdle()
        val tables: Set<CompositionData> = record.store

        // Walk the slot tree via mapTree (Compose 1.11+ API). Each callback receives a
        // SourceContext with the call's name, bounds, and source position. Returning null
        // skips a group; otherwise we emit a NodeJson and the runtime threads it through
        // to its parent so we can wire parentId in one pass.
        val nodes = mutableListOf<NodeJson>()
        val cache = ContextCache()
        val nextIdHolder = intArrayOf(1)
        tables.forEach { data ->
            data.mapTree<NodeJson>({ _, ctx, childNodes ->
                val box = ctx.bounds
                if (box.right <= box.left || box.bottom <= box.top) return@mapTree null
                val myId = nextIdHolder[0]
                nextIdHolder[0] = myId + 1
                val loc = ctx.location
                val node = NodeJson(
                    id = myId,
                    name = ctx.name ?: "Group",
                    x = box.left, y = box.top,
                    w = box.right - box.left, h = box.bottom - box.top,
                    sourceFileName = loc?.sourceFile,
                    packageHash = loc?.packageHash ?: 0,
                    line = loc?.lineNumber ?: -1,
                    parentId = null,
                )
                nodes.add(node)
                childNodes.forEach { it.parentId = myId }
                node
            }, cache)
        }

        // Walk the semantics tree to collect the rendered text strings — these are the
        // strings actually displayed on screen, after R.string lookups, lambdas, and any
        // other runtime substitution. Used by the report's search box.
        val renderedTexts = mutableListOf<String>()
        try {
            val rootSem = uiTest.onRoot().fetchSemanticsNode()
            collectRenderedText(rootSem, renderedTexts)
        } catch (t: Throwable) {
            System.err.println("[codeview] Could not collect semantics text for $previewId: ${t.message}")
        }

        outputDir.mkdirs()

        var bitmapWidth = 0
        var bitmapHeight = 0
        val pngFile = File(outputDir, "$previewId.png")
        try {
            val bitmap: Bitmap = uiTest.onRoot().captureToImage().asAndroidBitmap()
            bitmapWidth = bitmap.width
            bitmapHeight = bitmap.height
            pngFile.outputStream().use { os -> bitmap.compress(Bitmap.CompressFormat.PNG, 100, os) }
        } catch (t: Throwable) {
            System.err.println("[codeview] Skipping PNG capture for $previewId: ${t.message}")
        }

        val sidecar = File(outputDir, "$previewId.json")
        sidecar.writeText(buildJson(
            previewId = previewId,
            previewFqn = previewFqn,
            previewDisplayName = previewDisplayName,
            previewSourceFile = previewSourceFile,
            previewSourceLine = previewSourceLine,
            imageWidth = bitmapWidth,
            imageHeight = bitmapHeight,
            nodes = nodes,
            renderedTexts = renderedTexts,
        ))

        // For instrumented runs the app is uninstalled by AGP after the test, so files in
        // externalCacheDir disappear before the host can pull them. Use UiAutomation to shell-out
        // (uid 2000, has write access to /sdcard) and copy sidecars to a shared location that
        // survives uninstall. The sentinel file `__codeview_published__` flags this mode.
        if (File(outputDir, "__codeview_published__").exists()) {
            try {
                val ui = androidx.test.platform.app.InstrumentationRegistry
                    .getInstrumentation().uiAutomation
                val publishDir = "/sdcard/codeview-sidecars"
                ui.executeShellCommand("mkdir -p $publishDir").close()
                ui.executeShellCommand("chmod 777 $publishDir").close()
                sidecar.setReadable(true, false)
                if (pngFile.exists()) pngFile.setReadable(true, false)
                ui.executeShellCommand("cp ${sidecar.absolutePath} $publishDir/${sidecar.name}").close()
                if (pngFile.exists()) {
                    ui.executeShellCommand("cp ${pngFile.absolutePath} $publishDir/${pngFile.name}").close()
                }
            } catch (t: Throwable) {
                System.err.println("[codeview] Failed to publish sidecars: ${t.message}")
                t.printStackTrace()
            }
        }
    }

    private class NodeJson(
        val id: Int,
        val name: String,
        val x: Int, val y: Int, val w: Int, val h: Int,
        val sourceFileName: String?,
        val packageHash: Int,
        val line: Int,
        var parentId: Int?,
    )

    /**
     * Walks the semantics tree and appends every visible text-bearing string to [out].
     * Text comes from `Text` (rendered AnnotatedStrings), `EditableText` (TextField content),
     * and `ContentDescription`. Empty/blank strings are skipped.
     */
    private fun collectRenderedText(node: SemanticsNode, out: MutableList<String>) {
        val cfg = node.config
        cfg.getOrNull(SemanticsProperties.Text)?.forEach { ann ->
            val s = ann.text
            if (s.isNotBlank()) out.add(s)
        }
        cfg.getOrNull(SemanticsProperties.EditableText)?.let { ann ->
            val s = ann.text
            if (s.isNotBlank()) out.add(s)
        }
        cfg.getOrNull(SemanticsProperties.ContentDescription)?.forEach { s ->
            if (s.isNotBlank()) out.add(s)
        }
        node.children.forEach { collectRenderedText(it, out) }
    }

    private fun buildJson(
        previewId: String,
        previewFqn: String,
        previewDisplayName: String,
        previewSourceFile: String,
        previewSourceLine: Int,
        imageWidth: Int,
        imageHeight: Int,
        nodes: List<NodeJson>,
        renderedTexts: List<String>,
    ): String = buildString {
        append("{")
        append("\"schemaVersion\":1,")
        append("\"id\":").append(j(previewId)).append(',')
        append("\"previewFqn\":").append(j(previewFqn)).append(',')
        append("\"displayName\":").append(j(previewDisplayName)).append(',')
        append("\"sourceFile\":").append(j(previewSourceFile)).append(',')
        append("\"sourceLine\":").append(previewSourceLine).append(',')
        append("\"imageWidth\":").append(imageWidth).append(',')
        append("\"imageHeight\":").append(imageHeight).append(',')
        append("\"renderedTexts\":[")
        append(renderedTexts.joinToString(",") { j(it) })
        append("],")
        append("\"nodes\":[")
        append(nodes.joinToString(",") { n ->
            buildString {
                append('{')
                append("\"id\":").append(n.id).append(',')
                append("\"name\":").append(j(n.name)).append(',')
                append("\"bounds\":{\"x\":").append(n.x).append(",\"y\":").append(n.y)
                append(",\"width\":").append(n.w).append(",\"height\":").append(n.h).append("},")
                append("\"sourceFileName\":").append(if (n.sourceFileName == null) "null" else j(n.sourceFileName)).append(',')
                append("\"packageHash\":").append(n.packageHash).append(',')
                append("\"line\":").append(n.line).append(',')
                append("\"parentId\":").append(n.parentId?.toString() ?: "null")
                append('}')
            }
        })
        append("]}")
    }

    private fun j(s: String): String {
        val sb = StringBuilder(s.length + 2).append('"')
        for (c in s) when (c) {
            '\\' -> sb.append("\\\\")
            '"' -> sb.append("\\\"")
            '\n' -> sb.append("\\n")
            '\r' -> sb.append("\\r")
            '\t' -> sb.append("\\t")
            else -> if (c.code < 0x20) sb.append("\\u%04x".format(c.code)) else sb.append(c)
        }
        sb.append('"')
        return sb.toString()
    }
}
