// AUTO-GENERATED by codeview. Do not edit.
@file:OptIn(androidx.compose.ui.tooling.data.UiToolingDataApi::class, androidx.compose.ui.test.ExperimentalTestApi::class)
@file:Suppress("INVISIBLE_REFERENCE", "INVISIBLE_MEMBER")

package com.rohittp.plugables.codeview.generated

import android.graphics.Bitmap
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.tooling.CompositionData
import androidx.compose.runtime.tooling.LocalInspectionTables
import androidx.compose.ui.graphics.asAndroidBitmap
import androidx.compose.ui.test.ComposeUiTest
import androidx.compose.ui.test.captureToImage
import androidx.compose.ui.test.onRoot
import androidx.compose.ui.tooling.data.Group
import androidx.compose.ui.tooling.data.NodeGroup
import androidx.compose.ui.tooling.data.SourceLocation
import androidx.compose.ui.tooling.data.asTree
import java.io.File

object CodeviewRuntime {

    fun renderAndCapture(
        uiTest: ComposeUiTest,
        outputDir: File,
        previewId: String,
        previewFqn: String,
        previewDisplayName: String,
        previewSourceFile: String,
        previewSourceLine: Int,
        content: @Composable () -> Unit,
    ) {
        val tables = mutableSetOf<CompositionData>()
        uiTest.setContent {
            CompositionLocalProvider(LocalInspectionTables provides tables) {
                content()
            }
        }
        uiTest.waitForIdle()

        val nodes = mutableListOf<NodeJson>()
        val nextIdHolder = intArrayOf(1)
        tables.forEach { data ->
            walk(data.asTree(), parentId = null, nextIdHolder = nextIdHolder, out = nodes)
        }

        val bitmap: Bitmap = uiTest.onRoot().captureToImage().asAndroidBitmap()
        outputDir.mkdirs()
        val pngFile = File(outputDir, "$previewId.png")
        pngFile.outputStream().use { os -> bitmap.compress(Bitmap.CompressFormat.PNG, 100, os) }

        val sidecar = File(outputDir, "$previewId.json")
        sidecar.writeText(buildJson(
            previewId = previewId,
            previewFqn = previewFqn,
            previewDisplayName = previewDisplayName,
            previewSourceFile = previewSourceFile,
            previewSourceLine = previewSourceLine,
            imageWidth = bitmap.width,
            imageHeight = bitmap.height,
            nodes = nodes,
        ))
    }

    private data class NodeJson(
        val id: Int,
        val name: String,
        val x: Int, val y: Int, val w: Int, val h: Int,
        val sourceFileName: String?,
        val packageHash: Int,
        val line: Int,
        val parentId: Int?,
    )

    private fun walk(
        group: Group,
        parentId: Int?,
        nextIdHolder: IntArray,
        out: MutableList<NodeJson>,
    ) {
        val box = group.box
        val loc: SourceLocation? = group.location
        val name = (group as? NodeGroup)?.let { it.node::class.java.simpleName }
            ?: group.name?.toString()
            ?: "Group"
        if (box.right > box.left && box.bottom > box.top) {
            val myId = nextIdHolder[0]
            nextIdHolder[0] = myId + 1
            out.add(NodeJson(
                id = myId,
                name = name,
                x = box.left, y = box.top,
                w = box.right - box.left, h = box.bottom - box.top,
                sourceFileName = loc?.sourceFile,
                packageHash = loc?.packageHash ?: 0,
                line = loc?.lineNumber ?: -1,
                parentId = parentId,
            ))
            group.children.forEach { walk(it, myId, nextIdHolder, out) }
        } else {
            group.children.forEach { walk(it, parentId, nextIdHolder, out) }
        }
    }

    private fun buildJson(
        previewId: String,
        previewFqn: String,
        previewDisplayName: String,
        previewSourceFile: String,
        previewSourceLine: Int,
        imageWidth: Int,
        imageHeight: Int,
        nodes: List<NodeJson>,
    ): String = buildString {
        append("{")
        append("\"schemaVersion\":1,")
        append("\"id\":").append(j(previewId)).append(',')
        append("\"previewFqn\":").append(j(previewFqn)).append(',')
        append("\"displayName\":").append(j(previewDisplayName)).append(',')
        append("\"sourceFile\":").append(j(previewSourceFile)).append(',')
        append("\"sourceLine\":").append(previewSourceLine).append(',')
        append("\"imageWidth\":").append(imageWidth).append(',')
        append("\"imageHeight\":").append(imageHeight).append(',')
        append("\"nodes\":[")
        append(nodes.joinToString(",") { n ->
            buildString {
                append('{')
                append("\"id\":").append(n.id).append(',')
                append("\"name\":").append(j(n.name)).append(',')
                append("\"bounds\":{\"x\":").append(n.x).append(",\"y\":").append(n.y)
                append(",\"width\":").append(n.w).append(",\"height\":").append(n.h).append("},")
                append("\"sourceFileName\":").append(if (n.sourceFileName == null) "null" else j(n.sourceFileName)).append(',')
                append("\"packageHash\":").append(n.packageHash).append(',')
                append("\"line\":").append(n.line).append(',')
                append("\"parentId\":").append(n.parentId?.toString() ?: "null")
                append('}')
            }
        })
        append("]}")
    }

    private fun j(s: String): String {
        val sb = StringBuilder(s.length + 2).append('"')
        for (c in s) when (c) {
            '\\' -> sb.append("\\\\")
            '"' -> sb.append("\\\"")
            '\n' -> sb.append("\\n")
            '\r' -> sb.append("\\r")
            '\t' -> sb.append("\\t")
            else -> if (c.code < 0x20) sb.append("\\u%04x".format(c.code)) else sb.append(c)
        }
        sb.append('"')
        return sb.toString()
    }
}
