package com.rohittp.plugables.codeview

import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.SkipWhenEmpty
import org.gradle.api.tasks.TaskAction
import java.io.File

@CacheableTask
abstract class GeneratePreviewTestsTask : DefaultTask() {

    @get:InputFiles
    @get:SkipWhenEmpty
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val sourceDirs: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val testsOutputDir: DirectoryProperty

    @get:OutputDirectory
    abstract val sidecarOutputDir: DirectoryProperty

    @get:OutputFile
    abstract val indexOutputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val testsDir = testsOutputDir.get().asFile.apply { deleteRecursively(); mkdirs() }
        val sidecarDir = sidecarOutputDir.get().asFile.apply { mkdirs() }
        val indexFile = indexOutputFile.get().asFile.apply { parentFile.mkdirs() }

        val previews = sourceDirs.files.asSequence()
            .filter { it.exists() }
            .flatMap { it.walkTopDown().filter { f -> f.isFile && f.extension == "kt" } }
            .flatMap { PreviewSourceParser.parseFile(it).asSequence() }
            .toList()

        val pkgDir = File(testsDir, "com/rohittp/plugables/codeview/generated").apply { mkdirs() }
        File(pkgDir, "CodeviewRuntime.kt").writeText(loadHelper())

        previews.forEach { spec ->
            File(pkgDir, "${spec.id}Test.kt").writeText(renderTestClass(spec, sidecarDir.absolutePath))
        }

        indexFile.writeText(renderIndex(previews))
        logger.lifecycle("[codeview] Generated ${previews.size} preview test class(es).")
    }

    private fun loadHelper(): String =
        GeneratePreviewTestsTask::class.java.getResourceAsStream("/codeview-runtime-helpers.kt.tpl")
            ?.bufferedReader()?.use { it.readText() }
            ?: error("Missing /codeview-runtime-helpers.kt.tpl on classpath")

    private fun renderTestClass(spec: PreviewSpec, sidecarDir: String): String {
        val safeSidecarDir = sidecarDir.replace("\\", "\\\\")
        val safeSourceFile = (spec.source.file ?: "").replace("\\", "\\\\")
        return buildString {
            appendLine("// AUTO-GENERATED by codeview. Do not edit.")
            appendLine("@file:Suppress(\"unused\")")
            appendLine("package com.rohittp.plugables.codeview.generated")
            appendLine()
            appendLine("import androidx.compose.ui.test.junit4.createComposeRule")
            appendLine("import androidx.test.ext.junit.runners.AndroidJUnit4")
            appendLine("import org.junit.Rule")
            appendLine("import org.junit.Test")
            appendLine("import org.junit.runner.RunWith")
            appendLine("import java.io.File")
            appendLine()
            appendLine("@RunWith(AndroidJUnit4::class)")
            appendLine("class ${spec.id}Test {")
            appendLine("    @get:Rule val rule = createComposeRule()")
            appendLine()
            appendLine("    @Test")
            appendLine("    fun render() {")
            appendLine("        CodeviewRuntime.renderAndCapture(")
            appendLine("            rule = rule,")
            appendLine("            outputDir = File(\"$safeSidecarDir\"),")
            appendLine("            previewId = \"${spec.id}\",")
            appendLine("            previewFqn = \"${spec.previewFqn}\",")
            appendLine("            previewDisplayName = \"${spec.displayName}\",")
            appendLine("            previewSourceFile = \"$safeSourceFile\",")
            appendLine("            previewSourceLine = ${spec.source.line},")
            appendLine("        ) { ${spec.previewFqn}() }")
            appendLine("    }")
            appendLine("}")
        }
    }

    private fun renderIndex(previews: List<PreviewSpec>): String {
        val items = previews.joinToString(",") { spec ->
            buildString {
                append('{')
                append("\"id\":\"").append(spec.id).append("\",")
                append("\"previewFqn\":\"").append(spec.previewFqn).append("\",")
                append("\"displayName\":\"").append(spec.displayName).append("\",")
                append("\"sourceFile\":\"").append((spec.source.file ?: "").replace("\\", "\\\\")).append("\",")
                append("\"sourceLine\":").append(spec.source.line)
                append('}')
            }
        }
        return "{\"schemaVersion\":1,\"previews\":[$items]}"
    }
}
