package com.rohittp.plugables.viewmodelstub

/**
 * Generates two Kotlin source files from a [ViewModelInfo]:
 *  1. An **interface** whose name equals the Impl name minus the "Impl" suffix.
 *  2. A **stub** class (Impl name with "Impl" → "Stub") that implements the interface
 *     with constructor-parameter defaults for every state property and no-op methods.
 */
object StubRenderer {

    fun renderInterface(info: ViewModelInfo): String = buildString {
        appendLine("// GENERATED by GenerateViewModelStubsTask — do not edit.")
        appendLine("package ${info.packageName}")
        appendLine()
        if (info.imports.isNotEmpty()) {
            renderImports(this, info)
            appendLine()
        }
        appendLine("interface ${info.interfaceName} {")

        for (prop in info.properties) {
            val keyword = if (prop.isMutable) "var" else "val"
            appendLine("    $keyword ${prop.name}: ${prop.type}")
        }

        if (info.properties.isNotEmpty() && info.methods.isNotEmpty()) appendLine()

        for (method in info.methods) {
            val params = method.parameters
            append("    ")
            if (method.isSuspend) append("suspend ")
            appendLine("fun ${method.name}(")
            for ((pi, p) in params.withIndex()) {
                append("        ${p.name}: ${p.type}")
                if (p.type.trimEnd().endsWith("?")) append(" = null")
                if (pi < params.size - 1) append(",")
                appendLine()
            }
            append("    )")
            if (method.returnType != null) append(": ${method.returnType}")
            appendLine()
        }

        appendLine("}")
    }

    fun renderStub(info: ViewModelInfo): String = buildString {
        appendLine("// GENERATED by GenerateViewModelStubsTask — do not edit.")
        appendLine("package ${info.packageName}")
        appendLine()
        val extraImports = listOf(
            "import kotlinx.coroutines.flow.MutableStateFlow",
            "import kotlinx.coroutines.flow.MutableSharedFlow",
            "import androidx.lifecycle.MutableLiveData",
            "import kotlinx.coroutines.CoroutineScope",
            "import kotlinx.coroutines.SupervisorJob",
        )
        val allImports = (info.imports + extraImports).distinct()
        for (imp in allImports) appendLine(imp)
        appendLine()

        appendLine("class ${info.stubClassName}(")
        for ((i, prop) in info.properties.withIndex()) {
            val keyword = if (prop.isMutable) "override var" else "override val"
            val defaultExpr = defaultForType(prop.type.trim())
            val comma = if (i < info.properties.size - 1) "," else ""
            appendLine("    $keyword ${prop.name}: ${prop.type} = $defaultExpr$comma")
        }
        appendLine(") : ${info.interfaceName} {")

        for (method in info.methods) {
            append("    override ")
            if (method.isSuspend) append("suspend ")
            append("fun ${method.name}(")
            append(method.parameters.joinToString(", ") { "${it.name}: ${it.type}" })
            append(")")
            val ret = method.returnType
            if (ret != null) {
                append(": $ret")
                appendLine(" = ${defaultReturnValue(ret)}")
            } else {
                appendLine(" {}")
            }
        }

        appendLine("}")
    }

    private fun renderImports(sb: StringBuilder, info: ViewModelInfo) {
        for (imp in info.imports) sb.appendLine(imp)
    }

    fun defaultForType(type: String): String {
        if (type.endsWith("?")) return "null"

        val stateFlowInner = extractGenericArg(type, "StateFlow")
            ?: extractGenericArg(type, "MutableStateFlow")
        if (stateFlowInner != null) return "MutableStateFlow(${defaultForType(stateFlowInner)})"

        val sharedFlowInner = extractGenericArg(type, "SharedFlow")
            ?: extractGenericArg(type, "MutableSharedFlow")
        if (sharedFlowInner != null) return "MutableSharedFlow()"

        val liveDataInner = extractGenericArg(type, "LiveData")
            ?: extractGenericArg(type, "MutableLiveData")
        if (liveDataInner != null) return "MutableLiveData(${defaultForType(liveDataInner)})"

        return when (type) {
            "Boolean" -> "false"
            "Int" -> "0"
            "Long" -> "0L"
            "Float" -> "0f"
            "Double" -> "0.0"
            "String" -> "\"\""
            "Unit" -> "Unit"
            "CoroutineScope" -> "CoroutineScope(SupervisorJob())"
            else -> when {
                type.startsWith("List<") -> "emptyList()"
                type.startsWith("Map<") -> "emptyMap()"
                type.startsWith("Set<") -> "emptySet()"
                type.startsWith("ClosedFloatingPointRange<") -> "0f..1f"
                type.startsWith("IntRange") -> "0..0"
                else -> "TODO(\"Provide default for $type\")"
            }
        }
    }

    private fun defaultReturnValue(returnType: String): String {
        val type = returnType.trim()
        if (type.endsWith("?")) return "null"
        return when (type) {
            "Boolean" -> "false"
            "Int" -> "0"
            "Long" -> "0L"
            "Float" -> "0f"
            "Double" -> "0.0"
            "String" -> "\"\""
            "Unit" -> "Unit"
            "Job" -> "Job()"
            else -> when {
                type.startsWith("List<") -> "emptyList()"
                type.startsWith("Map<") -> "emptyMap()"
                type.startsWith("Set<") -> "emptySet()"
                else -> "TODO(\"Provide default for $type\")"
            }
        }
    }

    private fun extractGenericArg(type: String, wrapperName: String): String? {
        val idx = type.indexOf("$wrapperName<")
        if (idx == -1) return null
        val start = type.indexOf('<', idx)
        if (start == -1) return null
        var depth = 0
        for (i in start until type.length) {
            when (type[i]) {
                '<' -> depth++
                '>' -> {
                    depth--
                    if (depth == 0) return type.substring(start + 1, i).trim()
                }
            }
        }
        return null
    }
}
